import { Dimensions, StyleSheet, Platform } from "react-native";
import DefaultColors from "../common/style/DefaultColors";

const { width } = Dimensions.get("window");

export default StyleSheet.create({
	container: {
		flex: 1,
	},
	indicatorText: {
		zIndex: -1,
		top: 20,
		height: 120,
		paddingHorizontal: 20,
		paddingTop: 80,
		fontSize: 14,
		fontWeight: "400",
		borderRadius: 4,
		backgroundColor: DefaultColors.indicatorBackground,
		color: "#474747",
		overflow: "hidden",
	},
	content: {
		flex: 1,
		paddingHorizontal: 20,
		backgroundColor: "white",
	},
	information: {
		backgroundColor: "white",
		marginBottom: 5,
		marginTop: Platform.OS === "ios" ? 10 : 5,
		marginRight: 5,
		flexDirection: "column",
		alignItems: "flex-end",
		justifyContent: "center",
	},
	information2: {
		backgroundColor: "white",
		marginBottom: 10,
		marginRight: 5,
		flexDirection: "column",
		alignItems: "flex-end",
		justifyContent: "center",
	},
	infoTitle: {
		fontSize: 20,
		fontWeight: "bold",
	},
	infoText: {
		fontSize: 14,
	},
	amountContainer: {
		// flexDirection: "row",
		flexDirection: "column",
		justifyContent: "flex-start",
		// height: 60,
		height: "auto",
		paddingBottom: 5,
	},
	amountInputContainer: {
		flex: 1,
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		borderColor: "#bbb",
		borderBottomWidth: 1,
	},
	amountInput: {
		flex: 1,
		padding: 5,
		marginTop: 10,
		marginBottom: 10,
		marginRight: 15,
		color: "black",
		fontSize: 20,
	},
	amountButtonContainer: {
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 7,
		borderWidth: 1,
		borderColor: DefaultColors.lightGray,
		backgroundColor: "white",
		width: 45,
		height: 45,
		marginLeft: 15,
		marginRight: 8,

		shadowColor: "#000000",
		shadowRadius: 3,
		shadowOffset: { width: 1, height: 2 },
		shadowOpacity: 0.2,
		elevation: 5,
	},
	unitText: {
		fontSize: 18,
		color: "#383838",
		marginRight: 3,
	},
	maxText: {
		color: DefaultColors.secondColorToneDown,
		fontSize: 15,
		fontWeight: "bold",
	},
	addressContainer: {
		flexDirection: "row",
		height: 60,
		paddingBottom: 5,
	},
	addressInputContainer: {
		flex: 1,
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		borderColor: "#bbb",
		borderBottomWidth: 1,
	},
	addressInput: {
		flex: 1,
		padding: 5,
		justifyContent: "center",
		color: "black",
		fontSize: 18,
	},
	addressQrCode: {
		borderRadius: 7,
		borderWidth: 1,
		borderColor: DefaultColors.lightGray,
		width: 45,
		height: 45,
		justifyContent: "center",
		alignItems: "center",
		paddingLeft: 2,
		paddingTop: 2,
		marginLeft: 15,
		marginRight: 8,
		backgroundColor: "#fff",
		shadowColor: "#000000",
		shadowRadius: 3,
		shadowOffset: { width: 1, height: 2 },
		shadowOpacity: 0.2,
		elevation: 5,
	},
	boxButton: {
		borderRadius: 7,
		borderWidth: 1,
		borderColor: DefaultColors.lightGray,
		width: 95,
		height: 45,
		justifyContent: "center",
		alignItems: "center",
		paddingLeft: 2,
		paddingTop: 2,
		marginLeft: 3,
		marginRight: 0,
		backgroundColor: "#391b10",
		shadowColor: "#000000",
		shadowRadius: 3,
		shadowOffset: { width: 1, height: 2 },
		shadowOpacity: 0.2,
		elevation: 5,
	},
	feeTitleContainer: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginTop: 15,
		marginBottom: 5,
	},
	titleDetail: {
		alignItems: "flex-end",
		justifyContent: "center",
	},
	feeAdjust: {
		marginVertical: 5,
		backgroundColor: "#f4f4f4",
		borderRadius: 4,
		paddingBottom: 10,
	},
	feeDetail: {
		fontSize: 11,
		color: "#474747",
	},
	selectedFeeDetail: {
		fontSize: 11,
	},
	feeButton: {
		flex: 1,
		alignItems: "center",
		justifyContent: "center",
		borderColor: "#bbb",
	},
	feeTitleText: {
		color: "#474747",
	},
	selectedFeeTitleText: {
		color: "white",
	},
	sliderIcon: {
		width: "8%",
		alignItems: "center",
	},
	sliderContainer: {
		alignItems: "stretch",
		justifyContent: "center",
		width: "80%",
	},
	feeContainer: {
		flexDirection: "row",
		justifyContent: "flex-end",
		margin: 10,
		marginTop: 0,
		height: 25,
	},
	amountUnit: {
		justifyContent: "center",
		alignItems: "center",
		flexDirection: "row",
		right: 10,
	},
	feeInputText: {
		fontSize: 15,
		color: "#474747",
		paddingRight: 10,
	},
	feeText: {
		fontSize: 13,
		color: "#474747",
	},
	symbolText: {
		fontSize: 15,
		color: "#6e6e6e",
	},
	passwordContainer: {
		flexDirection: "row",
		alignItems: "center",
		height: 50,
		paddingBottom: 5,
	},
	passwordInputContainer: {
		flex: 1,
		height: 50,
		flexDirection: "row",
		justifyContent: "center",
		borderColor: "#bbb",
		borderBottomWidth: 1,
	},
	passwordInput: {
		flex: 1,
		padding: 5,
		marginRight: 15,
	},
	passwordUnit: {
		marginLeft: 2,
		marginRight: 5,
		justifyContent: "center",
	},
	submitContainer: {
		backgroundColor: "white",
		paddingBottom: 15,
		paddingTop: 15,
	},
	submitButton: {
		backgroundColor: "#bfbfbf",
		height: 55,
		width: width - 30,
		marginLeft: 15,
		marginRight: 15,
		borderRadius: 30,
		alignItems: "center",
		justifyContent: "center",
	},
	alertContainer: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		marginBottom: 10,
	},
	alertText: {
		fontSize: 12,
		color: "#6c6769",
	},
	modalContainer: {
		backgroundColor: "white",
		padding: 10,
		paddingTop: 5,
		justifyContent: "center",
		alignItems: "center",
		alignSelf: "center",
		borderColor: "rgba(0, 0, 0, 0.1)",
		width: width * 0.8,
		height: 260,
	},
	modalCloseButton: {
		alignSelf: "flex-end",
		marginTop: 5,
	},
	modalHeader: {
		alignItems: "center",
	},
	modalHeaderText: {
		fontSize: 25,
		marginTop: 10,
		color: "#474747",
		fontWeight: "bold",
	},
	modalContent: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	modalDetailText: {
		marginLeft: 40,
		marginRight: 40,
		textAlign: "center",
		fontSize: 11,
	},
	modalButton: {
		borderRadius: 25,
		borderWidth: 1,
		alignItems: "center",
		padding: 10,
		marginVertical: 0,
		borderColor: "white",
	},

	passwordModalContainer: {
		flex: 0,
		backgroundColor: "white",
		padding: 10,
		paddingTop: 5,
		justifyContent: "center",
		alignItems: "center",
		alignSelf: "center",
		borderRadius: 4,
		borderColor: "rgba(0, 0, 0, 0.1)",
		width: width * 0.8,
		height: 150,
	},
	passwordModalContent: {
		flex: 1,
		paddingHorizontal: 8,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	passwordModalDetailText: {
		fontSize: 13,
		textAlign: "center",
	},
	pinContainer: {
		flexDirection: "row",
		height: 60,
		paddingBottom: 5,
	},
	pinInputContainer: {
		flex: 1,
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		borderColor: "#bbb",
		borderBottomWidth: 1,
	},
	pinInput: {
		flex: 1,
		padding: 5,
		marginTop: 10,
		marginBottom: 10,
		marginRight: 15,
		color: "black",
		fontSize: 20,
	},
	emailContainer: {
		flexDirection: "row",
		height: 60,
		paddingBottom: 5,
	},
	emailInputContainer: {
		flex: 1,
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		borderColor: "#bbb",
		borderBottomWidth: 1,
	},
	emailInput: {
		flex: 1,
		padding: 5,
		marginTop: 10,
		marginBottom: 10,
		marginRight: 15,
		color: "black",
		fontSize: 20,
	},
	ecodeContainer: {
		flexDirection: "row",
		height: 60,
		paddingBottom: 5,
	},
	ecodeInputContainer: {
		flex: 1,
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		borderColor: "#bbb",
		borderBottomWidth: 1,
	},
	ecodeInput: {
		flex: 1,
		padding: 5,
		marginTop: 10,
		marginBottom: 10,
		marginRight: 15,
		color: "black",
		fontSize: 20,
	},
	ecodeCode: {
		borderRadius: 7,
		borderWidth: 1,
		borderColor: DefaultColors.lightGray,
		width: 95,
		height: 45,
		justifyContent: "center",
		alignItems: "center",
		paddingLeft: 2,
		paddingTop: 2,
		marginLeft: 15,
		marginRight: 8,
		backgroundColor: "#391b10",
		shadowColor: "#000000",
		shadowRadius: 3,
		shadowOffset: { width: 1, height: 2 },
		shadowOpacity: 0.2,
		elevation: 5,
	},
	amountQuickBtn: {
		marginLeft: -5,
	},
	amountButton: {
		backgroundColor: "#391b10",
		padding: 10,
		borderRadius: 3,
		marginTop: 5,
		marginRight: 5,
		marginLeft: 5,
		width: (Dimensions.get("window").width - 50) / 2,
		justifyContent: "center",
	},
});
